<?php
    namespace App\Core;

    /**
     * Created by PhpStorm.
     * User: sanzeeb
     * Date: 12/9/2015
     * Time: 10:36 AM
     */
    class CustomAppException extends \Exception {

        /**
         * (PHP 5 &gt;= 5.1.0)<br/>
         * Construct the exception. Note: The message is NOT binary safe.
         * @link http://php.net/manual/en/exception.construct.php
         * @param string $message [optional] The Exception message to throw.
         * @param int $code [optional] The Exception code.
         * @param Exception $previous [optional] The previous exception used for the exception chaining. Since 5.3.0
         */
        public function __construct($message = "", $code = 0, Exception $previous = null)
        {
            parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
        }

        /**
         * (PHP 5 &gt;= 5.1.0)<br/>
         * String representation of the exception
         * @link http://php.net/manual/en/exception.tostring.php
         * @return string the string representation of the exception.
         */
        public function __toString()
        {
            return $this->message;
           // parent::__toString(); // TODO: Change the autogenerated stub
        }

    }